# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6740455c73f872e648ea0dfacc079a9ac5de06fab6449aca8601e0921c8a766360dbbb968100dbe068ba2f237e5c1a2422e64d1957e54ed8e3c7be1ffc23e205

test:
  secret_key_base: 35043789cc35180597015ee20e826b7fc158cb99d20cca19d34c45970d4aa77f7270db24cc97f80f68acd9e190d6f84a1d39f72848f5b7e1af17196a6e86e3de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
